{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Presidio",
    "description" : "Context aware, pluggable and customizable PII anonymization service for text and images.",
    "contact" : {
      "name" : "Presidio support",
      "url" : "https://github.com/microsoft/presidio",
      "email" : "presidio@microsoft.com"
    },
    "license" : {
      "name" : "MIT",
      "url" : "https://github.com/microsoft/presidio/blob/master/LICENSE"
    },
    "version" : "2.0",
    "x-logo" : {
      "url" : "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg"
    }
  },
  "externalDocs" : {
    "description" : "Presidio documentation.",
    "url" : "https://microsoft.github.io/presidio/"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "tags" : [ {
    "name" : "Analyzer",
    "description" : "Detecting PII entities in text"
  }, {
    "name" : "Anonymizer",
    "description" : "Anonymizing detected PII text entities with desired values."
  } ],
  "paths" : {
    "/analyze" : {
      "post" : {
        "tags" : [ "Analyzer" ],
        "summary" : "Analyze Text",
        "description" : "Recognizes PII entities in a given text and returns their types, locations and score",
        "requestBody" : {
          "$ref" : "#/components/requestBodies/AnalyzeRequest"
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "description" : "A list analysis results",
                  "items" : {
                    "$ref" : "#/components/schemas/RecognizerResultWithAnaysisExplanation"
                  },
                  "x-content-type" : "application/json"
                },
                "examples" : {
                  "Enhanced response" : {
                    "value" : [ {
                      "entity_type" : "PERSON",
                      "start" : 0,
                      "end" : 10,
                      "score" : 0.85,
                      "analysis_explanation" : {
                        "recognizer" : "SpacyRecognizer",
                        "pattern_name" : null,
                        "pattern" : null,
                        "original_score" : 0.85,
                        "score" : 0.85,
                        "textual_explanation" : "Identified as PERSON by Spacy's Named Entity Recognition",
                        "score_context_improvement" : 0,
                        "supportive_context_word" : "",
                        "validation_result" : null
                      }
                    }, {
                      "entity_type" : "US_DRIVER_LICENSE",
                      "start" : 30,
                      "end" : 38,
                      "score" : 0.6499999999999999,
                      "analysis_explanation" : {
                        "recognizer" : "UsLicenseRecognizer",
                        "pattern_name" : "Driver License - Alphanumeric (weak)",
                        "pattern" : "\\\\b([A-Z][0-9]{3,6}|[A-Z][0-9]{5,9}|[A-Z][0-9]{6,8}|[A-Z][0-9]{4,8}|[A-Z][0-9]{9,11}|[A-Z]{1,2}[0-9]{5,6}|H[0-9]{8}|V[0-9]{6}|X[0-9]{8}|A-Z]{2}[0-9]{2,5}|[A-Z]{2}[0-9]{3,7}|[0-9]{2}[A-Z]{3}[0-9]{5,6}|[A-Z][0-9]{13,14}|[A-Z][0-9]{18}|[A-Z][0-9]{6}R|[A-Z][0-9]{9}|[A-Z][0-9]{1,12}|[0-9]{9}[A-Z]|[A-Z]{2}[0-9]{6}[A-Z]|[0-9]{8}[A-Z]{2}|[0-9]{3}[A-Z]{2}[0-9]{4}|[A-Z][0-9][A-Z][0-9][A-Z]|[0-9]{7,8}[A-Z])\\\\b",
                        "original_score" : 0.3,
                        "score" : 0.6499999999999999,
                        "textual_explanation" : null,
                        "score_context_improvement" : 0.3499999999999999,
                        "supportive_context_word" : "driver",
                        "validation_result" : null
                      }
                    } ]
                  },
                  "Lean response" : {
                    "value" : [ {
                      "analysis_explanation" : null,
                      "end" : 38,
                      "entity_type" : "US_DRIVER_LICENSE",
                      "score" : 0.6499999999999999,
                      "start" : 30
                    } ]
                  }
                }
              }
            }
          }
        },
        "servers" : [ {
          "url" : "https://presidio-analyzer-prod.azurewebsites.net"
        } ]
      }
    },
    "/recognizers" : {
      "get" : {
        "tags" : [ "Analyzer" ],
        "summary" : "Get Recognizers",
        "description" : "Get the available PII recognizers for a given language",
        "parameters" : [ {
          "name" : "language",
          "in" : "query",
          "description" : "Two characters for the desired language in ISO_639-1 format",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "en"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "description" : "A list of supported recognizers",
                  "items" : {
                    "type" : "string",
                    "description" : "Recognizer name"
                  },
                  "x-content-type" : "application/json"
                },
                "example" : [ "CryptoRecognizer", "CreditCardRecognizer", "IbanRecognizer", "UsPhoneRecognizer", "EmailRecognizer", "UsPassportRecognizer", "NhsRecognizer", "IpRecognizer", "SpacyRecognizer", "SgFinRecognizer", "UsSsnRecognizer", "UsBankRecognizer", "DomainRecognizer", "UsLicenseRecognizer", "UsItinRecognizer" ]
              }
            }
          }
        },
        "servers" : [ {
          "url" : "https://presidio-analyzer-prod.azurewebsites.net"
        } ]
      }
    },
    "/supportedentities" : {
      "get" : {
        "tags" : [ "Analyzer" ],
        "summary" : "Get supported entities",
        "description" : "Get the list of PII entities Presidio-Analyzer is capable of detecting",
        "parameters" : [ {
          "name" : "language",
          "in" : "query",
          "description" : "Two characters for the desired language in ISO_639-1 format",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "en"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "description" : "A list of supported entities",
                  "items" : {
                    "$ref" : "#/components/schemas/EntityTypes"
                  },
                  "x-content-type" : "application/json"
                },
                "example" : [ "PHONE_NUMBER", "US_DRIVER_LICENSE", "US_PASSPORT", "LOCATION", "CREDIT_CARD", "CRYPTO", "UK_NHS", "US_SSN", "US_BANK_NUMBER", "EMAIL_ADDRESS", "DATE_TIME", "IP_ADDRESS", "PERSON", "IBAN_CODE", "NRP", "US_ITIN", "DOMAIN_NAME" ]
              }
            }
          }
        },
        "servers" : [ {
          "url" : "https://presidio-analyzer-prod.azurewebsites.net"
        } ]
      }
    },
    "/anonymize" : {
      "post" : {
        "tags" : [ "Anonymizer" ],
        "summary" : "Anonymize Text",
        "requestBody" : {
          "$ref" : "#/components/requestBodies/AnonymizeRequest"
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/AnonymizeResponse"
                },
                "examples" : {
                  "Replace and Redact Anonymizers" : {
                    "value" : {
                      "text" : "hello world, my name is ANONYMIZED. My number is: ",
                      "items" : [ {
                        "operator" : "redact",
                        "entity_type" : "PHONE_NUMBER",
                        "start" : 50,
                        "end" : 50,
                        "text" : ""
                      }, {
                        "operator" : "replace",
                        "entity_type" : "NAME",
                        "start" : 24,
                        "end" : 34,
                        "text" : "ANONYMIZED"
                      } ]
                    }
                  },
                  "Replace as default Anonymizer" : {
                    "value" : {
                      "text" : "hello world, my name is ANONYMIZED. My number is: ANONYMIZED",
                      "items" : [ {
                        "operator" : "replace",
                        "entity_type" : "PHONE_NUMBER",
                        "start" : 50,
                        "end" : 60,
                        "text" : "ANONYMIZED"
                      }, {
                        "operator" : "replace",
                        "entity_type" : "NAME",
                        "start" : 24,
                        "end" : 34,
                        "text" : "ANONYMIZED"
                      } ]
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_400"
                }
              }
            }
          },
          "422" : {
            "description" : "Unprocessable Entity",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_422"
                }
              }
            }
          }
        },
        "servers" : [ {
          "url" : "https://presidio-anonymizer-prod.azurewebsites.net"
        } ]
      }
    },
    "/anonymizers" : {
      "get" : {
        "tags" : [ "Anonymizer" ],
        "summary" : "Get supported anonymizers",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "description" : "A list of all built-in supported anonymizers",
                  "items" : {
                    "type" : "string",
                    "description" : "The Anonymizer name",
                    "example" : "mask"
                  },
                  "x-content-type" : "application/json"
                },
                "example" : [ "hash", "mask", "redact", "replace", "encrypt" ]
              }
            }
          }
        },
        "servers" : [ {
          "url" : "https://presidio-anonymizer-prod.azurewebsites.net"
        } ]
      }
    },
    "/deanonymize" : {
      "post" : {
        "tags" : [ "Deanonymize" ],
        "summary" : "Deanonymize Text",
        "requestBody" : {
          "$ref" : "#/components/requestBodies/DeanonymizeRequest"
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/DeanonymizeResponse"
                },
                "examples" : {
                  "Decrypt Single PII" : {
                    "value" : {
                      "text" : "text_for_encryption",
                      "items" : [ {
                        "start" : 0,
                        "end" : 19,
                        "operator" : "decrypt",
                        "text" : "text_for_encryption",
                        "entity_type" : "NUMBER"
                      } ]
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_400"
                }
              }
            }
          },
          "422" : {
            "description" : "Unprocessable Entity",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_422"
                }
              }
            }
          }
        },
        "servers" : [ {
          "url" : "https://presidio-anonymizer-prod.azurewebsites.net"
        } ]
      }
    },
    "/deanonymizers" : {
      "get" : {
        "tags" : [ "Anonymizer" ],
        "summary" : "Get supported deanonymizers",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "description" : "A list of all built-in supported deanonymizers",
                  "items" : {
                    "type" : "string",
                    "description" : "The Deanonymizer name",
                    "example" : "decrypt"
                  },
                  "x-content-type" : "application/json"
                },
                "example" : [ "decrypt" ]
              }
            }
          }
        },
        "servers" : [ {
          "url" : "https://presidio-anonymizer-prod.azurewebsites.net"
        } ]
      }
    },
    "/health" : {
      "get" : {
        "tags" : [ "Anonymizer", "Analyzer" ],
        "summary" : "Healthcheck",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "string",
                  "example" : "Presidio Anonymizer service is up",
                  "x-content-type" : "text/plain"
                }
              }
            }
          }
        },
        "servers" : [ {
          "url" : "https://presidio-anonymizer-prod.azurewebsites.net"
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "AnalyzeRequest" : {
        "required" : [ "language", "text" ],
        "type" : "object",
        "properties" : {
          "text" : {
            "type" : "string",
            "description" : "The text to analyze",
            "example" : "hello world, my name is Jane Doe. My number is: 034453334"
          },
          "language" : {
            "type" : "string",
            "description" : "Two characters for the desired language in ISO_639-1 format",
            "example" : "en"
          },
          "correlation_id" : {
            "type" : "string",
            "description" : "A correlation id to append to headers and traces"
          },
          "score_threshold" : {
            "type" : "number",
            "description" : "The minimal detection score threshold",
            "format" : "double"
          },
          "entities" : {
            "type" : "array",
            "description" : "A list of entities to analyze",
            "items" : {
              "$ref" : "#/components/schemas/EntityTypes"
            }
          },
          "return_decision_process" : {
            "type" : "boolean",
            "description" : "Whether to include analysis explanation in the response"
          }
        }
      },
      "AnonymizeRequest" : {
        "required" : [ "analyzer_results", "text" ],
        "type" : "object",
        "properties" : {
          "text" : {
            "type" : "string",
            "description" : "The text to anonymize",
            "example" : "hello world, my name is Jane Doe. My number is: 034453334"
          },
          "anonymizers" : {
            "type" : "object",
            "description" : "Object where the key is DEFAULT or the ENTITY_TYPE and the value is the anonymizer definition"
          },
          "analyzer_results" : {
            "type" : "array",
            "description" : "Array of analyzer detections",
            "items" : {
              "$ref" : "#/components/schemas/RecognizerResult"
            }
          }
        }
      },
      "DeanonymizeRequest" : {
        "required" : [ "anonymizer_results", "deanonymizers", "text" ],
        "type" : "object",
        "properties" : {
          "text" : {
            "type" : "string",
            "description" : "The anonymized text",
            "example" : "My name is S184CMt9Drj7QaKQ21JTrpYzghnboTF9pn/neN8JME0="
          },
          "deanonymizers" : {
            "type" : "object",
            "description" : "Object where the key is DEFAULT or the ENTITY_TYPE and the value is decrypt since it is the only one supported"
          },
          "anonymizer_results" : {
            "type" : "array",
            "description" : "Array of anonymized PIIs",
            "items" : {
              "$ref" : "#/components/schemas/AnonymizerResult"
            }
          }
        }
      },
      "RecognizerResult" : {
        "required" : [ "end", "entity_type", "score", "start" ],
        "type" : "object",
        "properties" : {
          "start" : {
            "type" : "integer",
            "description" : "Where the PII starts",
            "example" : 24
          },
          "end" : {
            "type" : "integer",
            "description" : "Where the PII ends",
            "example" : 32
          },
          "score" : {
            "type" : "number",
            "description" : "The PII detection score",
            "format" : "double",
            "example" : 0.8
          },
          "entity_type" : {
            "$ref" : "#/components/schemas/EntityTypes"
          }
        }
      },
      "AnonymizerResult" : {
        "required" : [ "end", "entity_type", "start" ],
        "type" : "object",
        "properties" : {
          "start" : {
            "type" : "integer",
            "description" : "Where the anonymized PII starts",
            "example" : 24
          },
          "end" : {
            "type" : "integer",
            "description" : "Where the anonymized PII ends",
            "example" : 32
          },
          "entity_type" : {
            "$ref" : "#/components/schemas/EntityTypes"
          }
        }
      },
      "RecognizerResultWithAnaysisExplanation" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/RecognizerResult"
        }, {
          "type" : "object",
          "properties" : {
            "analysis_explanation" : {
              "$ref" : "#/components/schemas/AnalysisExplanation"
            }
          }
        } ]
      },
      "AnalysisExplanation" : {
        "type" : "object",
        "properties" : {
          "recognizer" : {
            "type" : "string",
            "description" : "Name of recognizer that made the decision"
          },
          "pattern_name" : {
            "type" : "string",
            "description" : "name of pattern (if decision was made by a PatternRecognizer)"
          },
          "pattern" : {
            "type" : "string",
            "description" : "Regex pattern that was applied (if PatternRecognizer)"
          },
          "original_score" : {
            "type" : "number",
            "description" : "Recognizer's confidence in result",
            "format" : "double"
          },
          "score" : {
            "type" : "number",
            "description" : "The PII detection score",
            "format" : "double"
          },
          "textual_explanation" : {
            "type" : "string",
            "description" : "Free text for describing a decision of a logic or model"
          },
          "score_context_improvement" : {
            "type" : "number",
            "description" : "Difference from the original score",
            "format" : "double"
          },
          "supportive_context_word" : {
            "type" : "string",
            "description" : "The context word which helped increase the score"
          },
          "validation_result" : {
            "type" : "number",
            "description" : "Result of a validation (e.g. checksum)",
            "format" : "double"
          }
        }
      },
      "EntityTypes" : {
        "type" : "string",
        "description" : "The supported PII entity types.",
        "example" : "PERSON"
      },
      "Replace" : {
        "title" : "Replace",
        "required" : [ "new_value", "type" ],
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "description" : "replace",
            "example" : "replace"
          },
          "new_value" : {
            "type" : "string",
            "description" : "The string to replace with",
            "example" : "VALUE"
          }
        },
        "description" : "Replace with a given value"
      },
      "Redact" : {
        "title" : "Redact",
        "required" : [ "type" ],
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "description" : "redact",
            "example" : "redact"
          }
        },
        "description" : "Replace with an empty string"
      },
      "Mask" : {
        "title" : "Mask",
        "required" : [ "chars_to_mask", "masking_char", "type" ],
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "description" : "mask",
            "example" : "mask"
          },
          "masking_char" : {
            "type" : "string",
            "description" : "The replacement character",
            "example" : "*"
          },
          "chars_to_mask" : {
            "type" : "integer",
            "description" : "The amount of characters that should be replaced",
            "example" : 4
          },
          "from_end" : {
            "type" : "boolean",
            "description" : "Whether to mask the PII from it's end",
            "example" : true,
            "default" : false
          }
        },
        "description" : "Replace with a given character"
      },
      "Hash" : {
        "title" : "Hash",
        "required" : [ "type" ],
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "description" : "hash",
            "example" : "hash"
          },
          "hash_type" : {
            "type" : "string",
            "description" : "The hashing algorithm",
            "example" : "md5",
            "default" : "md5",
            "enum" : [ "md5", "sha256", "sha512" ]
          }
        },
        "description" : "Replace with hashed value"
      },
      "Encrypt" : {
        "title" : "Encrypt",
        "required" : [ "key", "type" ],
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "description" : "encrypt",
            "example" : "encrypt"
          },
          "key" : {
            "type" : "string",
            "description" : "Cryptographic key of length 128, 192 or 256 bits, in a string format",
            "example" : "3t6w9z$C&F)J@NcR"
          }
        },
        "description" : "Replace with an encrypted value"
      },
      "Decrypt" : {
        "title" : "Decrypt",
        "required" : [ "key", "type" ],
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "description" : "decrypt",
            "example" : "decrypt"
          },
          "key" : {
            "type" : "string",
            "description" : "Cryptographic key of length 128, 192 or 256 bits, in a string format",
            "example" : "3t6w9z$C&F)J@NcR"
          }
        },
        "description" : "Replace encrypted PII decrypted text"
      },
      "AnonymizeResponse" : {
        "type" : "object",
        "properties" : {
          "text" : {
            "type" : "string"
          },
          "items" : {
            "type" : "array",
            "description" : "Array of anonymized entities",
            "items" : {
              "$ref" : "#/components/schemas/OperatorEntity"
            }
          }
        },
        "example" : {
          "text" : "text",
          "items" : [ {
            "entity_type" : "entity_type",
            "start" : 0,
            "end" : 6,
            "text" : "text",
            "operator" : "operator"
          }, {
            "entity_type" : "entity_type",
            "start" : 0,
            "end" : 6,
            "text" : "text",
            "operator" : "operator"
          } ]
        }
      },
      "OperatorEntity" : {
        "type" : "object",
        "properties" : {
          "operator" : {
            "type" : "string",
            "description" : "Name of the used operator"
          },
          "entity_type" : {
            "type" : "string",
            "description" : "Type of the PII entity"
          },
          "start" : {
            "type" : "integer",
            "description" : "Start index of the changed text"
          },
          "end" : {
            "type" : "integer",
            "description" : "End index in the changed text"
          },
          "text" : {
            "type" : "string",
            "description" : "The new text returned"
          }
        },
        "example" : {
          "entity_type" : "entity_type",
          "start" : 0,
          "end" : 6,
          "text" : "text",
          "operator" : "operator"
        }
      },
      "DeanonymizeResponse" : {
        "type" : "object",
        "properties" : {
          "text" : {
            "type" : "string"
          },
          "items" : {
            "type" : "array",
            "description" : "Array of deanonymized entities",
            "items" : {
              "$ref" : "#/components/schemas/OperatorEntity"
            }
          }
        },
        "example" : {
          "text" : "text",
          "items" : [ {
            "entity_type" : "entity_type",
            "start" : 0,
            "end" : 6,
            "text" : "text",
            "operator" : "operator"
          }, {
            "entity_type" : "entity_type",
            "start" : 0,
            "end" : 6,
            "text" : "text",
            "operator" : "operator"
          } ]
        }
      },
      "inline_response_400" : {
        "type" : "object",
        "properties" : {
          "error" : {
            "type" : "string",
            "example" : "Invalid request json"
          }
        }
      },
      "inline_response_422" : {
        "type" : "object",
        "properties" : {
          "error" : {
            "type" : "string",
            "example" : "Invalid input, text can not be empty"
          }
        }
      }
    },
    "responses" : {
      "400BadRequest" : {
        "description" : "Bad request",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/inline_response_400"
            }
          }
        }
      },
      "422UnprocessableEntity" : {
        "description" : "Unprocessable Entity",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/inline_response_422"
            }
          }
        }
      }
    },
    "requestBodies" : {
      "AnalyzeRequest" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/AnalyzeRequest"
            },
            "examples" : {
              "Minimal Request" : {
                "value" : {
                  "text" : "John Smith drivers license is AC432223",
                  "language" : "en"
                }
              },
              "Enhanced Request" : {
                "value" : {
                  "text" : "John Smith drivers license is AC432223",
                  "language" : "en",
                  "return_decision_process" : false,
                  "correlation_id" : "123e4567-e89b-12d3-a456-426614174000",
                  "score_threshold" : 0.6,
                  "entities" : [ "US_DRIVER_LICENSE" ],
                  "trace" : false
                }
              }
            }
          }
        },
        "required" : true
      },
      "AnonymizeRequest" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/AnonymizeRequest"
            },
            "examples" : {
              "Replace and Redact Anonymizers" : {
                "value" : {
                  "text" : "hello world, my name is Jane Doe. My number is: 034453334",
                  "anonymizers" : {
                    "PERSON" : {
                      "type" : "redact"
                    },
                    "PHONE_NUMBER" : {
                      "type" : "replace",
                      "new_value" : "ANONYMIZED"
                    }
                  },
                  "analyzer_results" : [ {
                    "start" : 24,
                    "end" : 32,
                    "score" : 0.8,
                    "entity_type" : "PERSON"
                  }, {
                    "start" : 48,
                    "end" : 57,
                    "score" : 0.95,
                    "entity_type" : "PHONE_NUMBER"
                  } ]
                }
              },
              "Replace as default Anonymizer" : {
                "value" : {
                  "text" : "hello world, my name is Jane Doe.",
                  "anonymizers" : {
                    "DEFAULT" : {
                      "type" : "replace",
                      "new_value" : "ANONYMIZED"
                    }
                  },
                  "analyzer_results" : [ {
                    "start" : 24,
                    "end" : 32,
                    "score" : 0.8,
                    "entity_type" : "PERSON"
                  } ]
                }
              }
            }
          }
        },
        "required" : true
      },
      "DeanonymizeRequest" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/DeanonymizeRequest"
            },
            "examples" : {
              "Deanonymize text" : {
                "value" : {
                  "text" : "My name is S184CMt9Drj7QaKQ21JTrpYzghnboTF9pn/neN8JME0=",
                  "deanonymizers" : {
                    "PERSON" : {
                      "type" : "decrypt",
                      "key" : "WmZq4t7w!z%C&F)J"
                    }
                  },
                  "anonymizer_results" : [ {
                    "start" : 11,
                    "end" : 55,
                    "entity_type" : "PERSON"
                  } ]
                }
              }
            }
          }
        },
        "required" : true
      }
    }
  }
}
